### ISSUE TITLE
Source Configuration - Seeing and Setting Bypass Proxy and Allow Self-Service on a Source doesn't work

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#455]
This is not pulling the data properly, nor is it setting it. Something is not getting set correctly in the binding to make this setting take. I am somewhat limited on WPF to see what it may be.

**Comment by ferventcoder** [comment]
I did add this to the mapper configuration (AutoMapper) as the names are different:

~~~cs
config.CreateMap<ConfigFileSourceSetting, ChocolateySource>()
                    .ForMember(dest => dest.ByPassProxy, opt => opt.MapFrom(src => src.BypassProxy))
                    .ForMember(dest => dest.SelfService, opt => opt.MapFrom(src => src.AllowSelfService));
~~~

I'm not sure if the mapper configuration setup pulls things back correctly though.

**Comment by RichiCoder1** [comment]
Derp. Proper solution would like be to simply change the `ChocolateySource` properties.

**Comment by ferventcoder** [comment]
To match the ConfigSettings? Yeah, likely to work best.

**Comment by ferventcoder** [comment]
The following affects this fix - https://github.com/chocolatey/choco/issues/1394

**Comment by ferventcoder** [comment]
Are we sure this is fixed?

**Comment by gep13** [comment]
@ferventcoder this ticket was closed automagically as a result of the comment in your PR.

I tried to test it out at lunch time, however, I was running into other issues.  You around tonight for a quick conversation?

**Comment by ferventcoder** [comment]
Yes sir. Just ping me when you are ready.

**Comment by gep13** [comment]
@ferventcoder yeah, just tested this, and no, it still isn't working 😢

**Comment by gep13** [comment]
@ferventcoder as discussed, this should now be taken care of, and the latest version on MyGet (`0.14.0-unstable0299`) should include this functionality.
